# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('age', models.IntegerField(default=1, unique=True)),
                ('current_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
