# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-03-12 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0002_auto_20200311_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('data', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
